#include <string.h>
#include "frame_types.h"

char* get_type(const char *name)
{

  if(!strcmp(name, "Audio encryption")) return "AENC";
  else if(!strcmp(name, "Attached picture")) return "APIC";
  else if(!strcmp(name, "Comments")) return "COMM";
  else if(!strcmp(name, "Commercial frame")) return "COMR";
  else if(!strcmp(name, "Encryption method registration")) return "ENCR";
  else if(!strcmp(name, "Equalization")) return "EQUA";
  else if(!strcmp(name, "Event timing codes")) return "ETCO";
  else if(!strcmp(name, "General encapsulated object")) return "GEOB"; 
  else if(!strcmp(name, "Group identification registration")) return "GRID"; 
  else if(!strcmp(name, "Involved people list")) return "IPLS"; 
  else if(!strcmp(name, "Linked information")) return "LINK"; 
  else if(!strcmp(name, "Music CD identifier")) return "MCDI"; 
  else if(!strcmp(name, "MPEG location lookup table")) return "MLLT"; 
  else if(!strcmp(name, "Ownership frame")) return "OWNE"; 
  else if(!strcmp(name, "Private frame")) return "PRIV"; 
  else if(!strcmp(name, "Play counter")) return "PCNT"; 
  else if(!strcmp(name, "Popularimeter")) return "POPM"; 
  else if(!strcmp(name, "Position synchronisation frame")) return "POSS"; 
  else if(!strcmp(name, "Recommended buffer size")) return "RBUF"; 
  else if(!strcmp(name, "Relative volume adjustment")) return "RVAD"; 
  else if(!strcmp(name, "Reverb")) return "RVRB"; 
  else if(!strcmp(name, "Synchronized lyric/text")) return "SYLT"; 
  else if(!strcmp(name, "Synchronized tempo codes")) return "SYTC"; 
  else if(!strcmp(name, "Album/Movie/Show title")) return "TALB"; 
  else if(!strcmp(name, "BPM (beats per minute)")) return "TBPM"; 
  else if(!strcmp(name, "Composer")) return "TCOM"; 
  else if(!strcmp(name, "Content type")) return "TCON"; 
  else if(!strcmp(name, "Copyright message")) return "TCOP"; 
  else if(!strcmp(name, "Date")) return "TDAT"; 
  else if(!strcmp(name, "Playlist delay")) return "TDLY"; 
  else if(!strcmp(name, "Encoded by")) return "TENC"; 
  else if(!strcmp(name, "Lyricist/Text writer")) return "TEXT"; 
  else if(!strcmp(name, "File type")) return "TFLT"; 
  else if(!strcmp(name, "Time")) return "TIME"; 
  else if(!strcmp(name, "Content group description")) return "TIT1"; 
  else if(!strcmp(name, "Title/songname/content description")) return "TIT2"; 
  else if(!strcmp(name, "Subtitle/Description refinement")) return "TIT3"; 
  else if(!strcmp(name, "Initial key")) return "TKEY"; 
  else if(!strcmp(name, "Language(s)")) return "TLAN"; 
  else if(!strcmp(name, "Length")) return "TLEN"; 
  else if(!strcmp(name, "Media type")) return "TMED"; 
  else if(!strcmp(name, "Original album/movie/show title")) return "TOAL"; 
  else if(!strcmp(name, "Original filename")) return "TOFN"; 
  else if(!strcmp(name, "Original lyricist(s)/text writer(s)")) return "TOLY"; 
  else if(!strcmp(name, "Original artist(s)/performer(s)")) return "TOPE"; 
  else if(!strcmp(name, "Original release year")) return "TORY"; 
  else if(!strcmp(name, "File owner/licensee")) return "TOWN"; 
  else if(!strcmp(name, "Lead performer(s)/Soloist(s)")) return "TPE1"; 
  else if(!strcmp(name, "Band/orchestra/accompaniment")) return "TPE2"; 
  else if(!strcmp(name, "Conductor/performer refinement")) return "TPE3"; 
  else if(!strcmp(name, "Interpreted, remixed, or otherwise modified by")) return "TPE4"; 
  else if(!strcmp(name, "Part of a set")) return "TPOS"; 
  else if(!strcmp(name, "Publisher")) return "TPUB"; 
  else if(!strcmp(name, "Track number/Position in set")) return "TRCK"; 
  else if(!strcmp(name, "Recording dates")) return "TRDA"; 
  else if(!strcmp(name, "Internet radio station name")) return "TRSN"; 
  else if(!strcmp(name, "Internet radio station owner")) return "TRSO"; 
  else if(!strcmp(name, "Size")) return "TSIZ"; 
  else if(!strcmp(name, "ISRC (international standard recording code)")) return "TSRC"; 
  else if(!strcmp(name, "Software/Hardware and settings used for encoding")) return "TSSE"; 
  else if(!strcmp(name, "Year")) return "TYER"; 
  else if(!strcmp(name, "User defined text information frame")) return "TXXX"; 
  else if(!strcmp(name, "Unique file identifier")) return "UFID"; 
  else if(!strcmp(name, "Terms of use")) return "USER"; 
  else if(!strcmp(name, "Unsychronized lyric/text transcription")) return "USLT"; 
  else if(!strcmp(name, "Commercial information")) return "WCOM"; 
  else if(!strcmp(name, "Copyright/Legal information")) return "WCOP";
  else if(!strcmp(name, "Official audio file webpage")) return "WOAF"; 
  else if(!strcmp(name, "Official artist/performer webpage")) return "WOAR"; 
  else if(!strcmp(name, "Official audio source webpage")) return "WOAS"; 
  else if(!strcmp(name, "Official internet radio station homepage")) return "WORS"; 
  else if(!strcmp(name, "Payment")) return "WPAY"; 
  else if(!strcmp(name, "Publishers official webpage")) return "WPUB"; 
  else if(!strcmp(name, "User defined URL link frame")) return "WXXX"; 
}
